"""add_pipeline_status_values

Revision ID: f61c9520272e
Revises: 003_firmware_analysis
Create Date: 2026-03-12 04:12:22.889667
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f61c9520272e'
down_revision: Union[str, None] = '003_firmware_analysis'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('firmware_analyses', 'current_stage',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('firmware_analyses', 'total_stages',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('firmware_analyses', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('hosts', 'is_up',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('hosts', 'open_port_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('hosts', 'discovered_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('hosts', 'last_seen',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('ports', 'discovered_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('scan_logs', 'level',
               existing_type=sa.VARCHAR(length=16),
               nullable=False)
    op.alter_column('scan_logs', 'timestamp',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('scans', 'current_stage',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('scans', 'total_stages',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('scans', 'hosts_discovered',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('scans', 'live_hosts',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('scans', 'open_ports_found',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('scans', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('tags', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tags', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('scans', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('scans', 'open_ports_found',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('scans', 'live_hosts',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('scans', 'hosts_discovered',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('scans', 'total_stages',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('scans', 'current_stage',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('scan_logs', 'timestamp',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('scan_logs', 'level',
               existing_type=sa.VARCHAR(length=16),
               nullable=True)
    op.alter_column('ports', 'discovered_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('hosts', 'last_seen',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('hosts', 'discovered_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('hosts', 'open_port_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('hosts', 'is_up',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('firmware_analyses', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('firmware_analyses', 'total_stages',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('firmware_analyses', 'current_stage',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
